### PR TITLE
Add some PWM-enabled Pins

### PR DESCRIPTION
**Pull request by alt-romes**
I needed these Pins for my project, but I don't know how to classify them. If you let me know how to figure it out I can add the proper comments and we can upstream this change.

### CODE REVIEW

**Comment by WJWH** [comment]
I'm not entirely sure why these pins are not already there :thinking: . AFAICT they are present in all of the current RPi models so there's not really a reason not to add them.

I guess you could just add them as `Pin32|Pin33|Pin35` like you've already done, with a label like "general GPIO pins" or something? You could probably also add them in with the other `Pin123` constructors already present.

**Comment by alt-romes** [comment]
I've added them in with the remaining ones.

**Comment by WJWH** [comment]
Thanks! I'll make a new release somewhere this week.

**Comment by WJWH** [comment]
v0.11.0 is live on Hackage.

**Comment by alt-romes** [comment]
> v0.11.0 is live on Hackage.

Thanks, much appreciated.

**Pull request merged**
