### PR TITLE
feat: add SPI management functions (bit order and clock divider)

### PR DESCRIPTION
**Pull request by michivi**
Hi,

This just adds two functions that were missing for SPI communications (`bcm2835_spi_setBitOrder` as `setBitOrderSPI` and `bcm2835_spi_setClockDivider` as`setClockDividerSPI`) and required for some personal projects using that protocol.

Have a nice day!

### CODE REVIEW

**Comment by WJWH** [comment]
Thanks for the contribution! I have never needed this functionality but would be happy to include it. One question though: in the [documentation](https://www.airspayce.com/mikem/bcm2835/group__spi.html#ga4c9428d73eb17354022234c89dadce9b) for the bcm library, it states that due to the minimum and maximum clock speeds of the SPI, not the entire range of a `uint16` is valid as an input for `bcm2835_aux_spi_setClockDivider()`. Is this a problem for your use case or should we integrate the functionality of `bcm2835_aux_spi_CalcClockDivider()` as well?

**Comment by michivi** [comment]
For my use case, my target was a specific clock divider, not a frequency, so I could use `bcm2835_spi_setClockDivider` directly.

Before adding this function call though, I was wondering whether to use `Word16` as parameter, or an enum. But if I understood the `bcm2835` documentation correctly, some have reported that they've successfully used values outside the predefined ones. Also, the HPi library didn't use enums for clock dividers so I thought this way would be more consistent.

I'm not using `bcm2835_aux_spi_CalcClockDivider` as my current case is working on the SPI (0) channel, not the AUX SPI (1). Though you may see in the near future another PR for AUX SPI as well, as it is highly likely that I'll need it as well :-)

**Comment by WJWH** [comment]
If you don't need it yet, I'm happy to YAGNI this issue and merge as is :+1:.

I don't think an enum would be the best way in any case, since there would potentially be many many values. Maybe we can 'just' clamp the value so that it's always in the valid range that the documentation provides?

**Comment by michivi** [comment]
I'll make another PR for the AUX SPI, when I'll need it ^^

I don't think we need to clamp the value, as the function literally expects a value between 0 and 65535, which makes `Word16` good for it.

**Review by WJWH — APPROVED** [review]

**Comment by WJWH** [comment]
I released a new version with version number 0.6.0 that contains your changes.

**Pull request merged**
